FROM python:3.9-slim-bullseye

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install dependencies:
COPY api/requirements.txt .
RUN pip install -r requirements.txt

# Run the application:
COPY api/api.py .
CMD ["python", "api.py"]
